import {type Field} from './ui';
import {type Records,areas} from './model';
import {dateKey} from './logic';
const field=(key:string,label:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label,type,...extra});
export const title=field('title','Title','text',{required:true,wide:true});
export const notes=field('notes','Notes','textarea');
export const area=field('area','Area','select',{options:areas,required:true,default:'Tawjihi'});
export const date=(key:string,label:string,required=true)=>field(key,label,'date',{required,default:required?dateKey():null});
export const select=(key:string,label:string,options:Field['options'],required=true,def?:string)=>field(key,label,'select',{options,required,default:def??(typeof options?.[0]==='string'?options[0]:'')});
export const number=(key:string,label:string,def=0,max=100000,min=0)=>field(key,label,'number',{default:def,min,max,required:true});
export const relation=(key:string,label:string,rows:Records[keyof Records],required=false)=>select(key,label,rows.map(r=>({value:r.id,label:String(r.name??r.title??r.filename)})),required,required?rows[0]?.id:'');
export function taskFields(db:Records):Field[]{return [title,field('description','Description','textarea'),area,relation('subject_id','Subject',db.subjects),relation('topic_id','Topic',db.topics),date('due_date','Planned date'),field('due_time','Due time','time'),number('planned_minutes','Planned minutes',30,1440,1),select('priority','Priority',['normal','high','low']),select('status','Status',['planned','in_progress','completed','skipped','cancelled']),select('recurrence','Repeat',['none','daily','weekly']),relation('exam_id','Linked exam',db.exams),relation('file_id','Linked file',db.files)];}
export const mistakeFields=(db:Records):Field[]=>[title,area,relation('subject_id','Subject',db.subjects),relation('topic_id','Topic',db.topics),field('question_number','Question ID / number'),select('category','Mistake type',['concept','calculation','forgot_rule','misread','careless','time_management','memorization','wrong_method','guessed','other']),field('explanation','What went wrong?','textarea'),field('correct_approach','Correct approach','textarea'),date('review_date','Review date'),select('status','Status',['new','review_due','reviewing','improving','mastered'])];
export const examFields=(db:Records):Field[]=>[title,relation('subject_id','Subject',db.subjects,true),relation('topic_id','Topic',db.topics),select('exam_type','Exam type',['monthly','quiz','final','practice']),date('exam_date','Exam date'),field('score','Score','number',{min:0}),number('maximum_score','Maximum score',100,10000,1),field('teacher','Teacher'),notes];
export const universityFields:Field[]=[field('name','University name','text',{required:true}),field('country','Country'),field('program','Program'),date('deadline','Deadline',false),field('platform','Application platform'),select('status','Status',['researching','interested','applying','submitted','accepted','rejected','waitlisted','withdrawn']),field('url','Website','url'),notes];
export const achievementFields:Field[]=[title,select('kind','Type',['Project','Competition','Award','Volunteer work','Course','Leadership','Work','Club','Research','Other']),field('organization','Organization'),field('role','Role'),date('start_date','Start date',false),date('end_date','End date',false),field('description','Description','textarea'),field('impact','Impact / result','textarea'),field('common_app_candidate','Common App candidate','checkbox'),field('cv_candidate','CV candidate','checkbox')];
