import { type Row, num, str } from './model';
export const normalizeAnswer=(s:string)=>s.trim().toLocaleUpperCase('en-US');
export const grade=(a:string,b:string):'ungraded'|'correct'|'incorrect'=>!a.trim()||!b.trim()?'ungraded':normalizeAnswer(a)===normalizeAnswer(b)?'correct':'incorrect';
export const parseIds=(s:string)=>s.trim().split(/[\s,;]+/).map(v=>v.trim()).filter(Boolean);
export const percentage=(value:number,max:number)=>max>0?Math.round(100*value/max):0;
export const examPercentage=(score:number,max:number)=>{if(max<=0||score<0||score>max)throw new Error('Score must be between zero and a positive maximum.');return percentage(score,max)};
export function satStats(rows:Row[],seconds:number) {const graded=rows.filter(r=>grade(str(r.my_answer_raw),str(r.correct_answer_raw))!=='ungraded');const correct=graded.filter(r=>grade(str(r.my_answer_raw),str(r.correct_answer_raw))==='correct').length;return {correct,wrong:graded.length-correct,ungraded:rows.length-graded.length,accuracy:percentage(correct,graded.length),average:rows.length?seconds/rows.length:0,unique:new Set(rows.map(r=>str(r.question_identifier).trim()).filter(Boolean)).size};}
export const duplicateAttempts=(id:string,rows:Row[],excludeSession:string)=>rows.filter(r=>str(r.question_identifier).trim()===id.trim()&&r.session_id!==excludeSession&&id.trim()!=='');
export const dateKey=(date:Date|string=new Date(),timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone)=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(date));
export const shiftDay=(day:string,n:number)=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export const nextReview=(day:string,successfulReviews:number,intervals=[1,3,7,14])=>shiftDay(day,intervals[Math.min(successfulReviews,intervals.length-1)]??14);
export function dailyScore(tasks:Row[],minutes:number,target:number){const active=tasks.filter(t=>!['cancelled','skipped'].includes(str(t.status)));if(!active.length&&minutes===0)return 0;const done=(a:Row[])=>a.length?a.filter(t=>t.status==='completed').length/a.length:1;const review=active.filter(t=>t.source==='mistake_review');const urgent=active.filter(t=>t.priority==='high'||t.source==='exam_preparation');return Math.round(50*done(active)+20*Math.min(1,minutes/Math.max(1,target))+15*done(review)+15*done(urgent));}
export function streak(scores:Record<string,number>,today:string,threshold=70,rest:number[]=[],preserve=true){const days=Object.keys(scores).sort();if(!days.length)return {current:0,longest:0,productive:0,perfect:0};let run=0,longest=0,productive=0,perfect=0,current=0;for(let d=days[0];d<=today;d=shiftDay(d,1)){const score=scores[d]??0;const isRest=preserve&&rest.includes(new Date(d+'T12:00:00Z').getUTCDay());if(score>=threshold){run++;productive++;if(score===100)perfect++;}else if(!isRest&&d!==today)run=0;longest=Math.max(longest,run);current=run;}return {current,longest,productive,perfect};}
export const readiness=(rows:Row[])=>percentage(rows.filter(r=>r.status==='completed').length,rows.length);
export const duration=(seconds:number)=>{const n=Math.max(0,Math.floor(seconds));return `${String(Math.floor(n/3600)).padStart(2,'0')}:${String(Math.floor(n/60)%60).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
export const elapsed=(row:Row,now=Date.now())=>num(row.elapsed_seconds)+(row.running_since?Math.max(0,(now-new Date(str(row.running_since)).getTime())/1000):0);
export const wordCount=(s:string)=>s.trim()?s.trim().split(/\s+/).length:0;
