import {useState,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {useForm} from 'react-hook-form';
import {z} from 'zod';
import {X,Plus,Trash2,PenLine,FolderOpen,ArrowUpRight} from 'lucide-react';
import {useStore} from './store';
import {type Row,type Table,type Value,str,num} from './model';
export const errorMessage=(e:unknown)=>e instanceof Error?e.message:typeof e==='object'&&e&&'message'in e?String(e.message):'Something went wrong. Please retry.';
export function Empty({title,detail,children}:{title:string;detail?:string;children?:ReactNode}){return <div className="empty"><FolderOpen size={30}/><h3>{title}</h3>{detail&&<p>{detail}</p>}{children}</div>}
export function PageTitle({title,eyebrow,children}:{title:string;eyebrow?:string;children?:ReactNode}){return <header className="page-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1></div><div className="actions">{children}</div></header>}
export function Stat({label,value,detail}:{label:string;value:ReactNode;detail?:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>}
export function Pill({children,tone='purple'}:{children:ReactNode;tone?:string}){return <span className={`pill ${tone}`}>{children}</span>}
export interface Field {key:string;label:string;type?:'text'|'number'|'date'|'time'|'textarea'|'select'|'checkbox'|'url';required?:boolean;options?:(string|{value:string;label:string})[];min?:number;max?:number;step?:number;default?:Value;wide?:boolean;help?:string}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="modal"><div className="modal-heading"><Dialog.Title>{title}</Dialog.Title><Dialog.Close className="icon-button" aria-label="Close dialog"><X size={20}/></Dialog.Close></div><Dialog.Description className={description?'muted':'sr-only'}>{description??title}</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export function RecordForm({fields,initial={},onSubmit,onCancel,submitLabel='Save'}:{fields:Field[];initial?:Partial<Row>;onSubmit:(data:Partial<Row>)=>Promise<void>;onCancel:()=>void;submitLabel?:string}){
 const values:Record<string,Value>={};for(const f of fields)values[f.key]=initial[f.key]??f.default??(f.type==='checkbox'?false:'');
 const {register,handleSubmit,formState:{errors,isSubmitting},setError}=useForm<Record<string,Value>>({defaultValues:values});const [error,setErr]=useState('');
 const submit=handleSubmit(async values=>{setErr('');const parsed:Partial<Row>={};for(const f of fields){let v=values[f.key];if(f.type==='number'){v=v===''?null:Number(v);if(v!==null){const schema=z.number().finite().min(f.min??-Infinity).max(f.max??Infinity);if(!schema.safeParse(v).success){setError(f.key,{message:'Enter a valid number within the allowed range.'});return}}}else if(f.type!=='checkbox')v=String(v??'').trim();if(f.required&&(v===''||v===null)){setError(f.key,{message:'This field is required.'});return}if(f.type==='url'&&v&&!z.url().safeParse(v).success){setError(f.key,{message:'Enter a complete URL.'});return}parsed[f.key]=v===''&&['date','time','number'].includes(f.type??'')?null:v;}
 try{await onSubmit(parsed)}catch(e){setErr(errorMessage(e))}});
 return <form onSubmit={submit} className="form"><div className="form-grid">{fields.map(f=><label key={f.key} className={f.wide||f.type==='textarea'?'wide':''}><span>{f.label}{f.required?' *':''}</span>{f.type==='select'?<select {...register(f.key)}>{!f.required&&<option value="">None</option>}{f.options?.map(o=>typeof o==='string'?<option key={o} value={o}>{o.replaceAll('_',' ')}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea rows={f.key==='response'?10:3} {...register(f.key)}/>:<input type={f.type??'text'} min={f.min} max={f.max} step={f.step??(f.type==='number'?1:undefined)} {...register(f.key)}/>} {f.help&&<small>{f.help}</small>}{errors[f.key]&&<small className="error-text">{errors[f.key]?.message}</small>}</label>)}</div>{error&&<p role="alert" className="error-box">{error}</p>}<footer className="form-footer"><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button disabled={isSubmitting} className="button">{isSubmitting?'Saving…':submitLabel}</button></footer></form>
}
export function Editor({table,title,fields,initial,onClose,defaults={},afterSave}:{table:Table;title:string;fields:Field[];initial?:Row;onClose:()=>void;defaults?:Partial<Row>;afterSave?:(row:Row)=>void}){const {save,notify}=useStore();return <Modal open onClose={onClose} title={title}><RecordForm fields={fields} initial={{...defaults,...initial}} onCancel={onClose} onSubmit={async d=>{const row=await save(table,{...defaults,...d,...(initial?{id:initial.id}:{})});notify('Saved');afterSave?.(row);onClose()}}/></Modal>}
export function Collection({table,title,fields,filter=()=>true,defaults={},render,addLabel,description}:{table:Table;title:string;fields:Field[];filter?:(r:Row)=>boolean;defaults?:Partial<Row>;render?:(r:Row)=>ReactNode;addLabel?:string;description?:string}){const {db,remove,notify}=useStore();const [edit,setEdit]=useState<Row|'new'|null>(null),[deleting,setDeleting]=useState<Row|null>(null),[search,setSearch]=useState('');const rows=db[table].filter(filter).filter(r=>Object.values(r).join(' ').toLowerCase().includes(search.toLowerCase()));return <section className="panel"><div className="section-heading"><div><h2>{title}</h2>{description&&<p className="muted">{description}</p>}</div><button className="button" onClick={()=>setEdit('new')}><Plus size={17}/>{addLabel??'Add'}</button></div><input className="search-input" aria-label={`Search ${title}`} placeholder={`Search ${title.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)}/>{rows.length?<div className="record-list">{rows.map(r=><article key={r.id} className="record"><div className="record-body">{render?render(r):<><h3>{str(r.title??r.name)}</h3><p>{str(r.description??r.notes)}</p></>}</div><div className="record-actions"><button className="icon-button" aria-label={`Edit ${r.title??r.name}`} onClick={()=>setEdit(r)}><PenLine size={17}/></button><button className="icon-button" aria-label={`Delete ${r.title??r.name}`} onClick={()=>setDeleting(r)}><Trash2 size={17}/></button></div></article>)}</div>:<Empty title={`No ${title.toLowerCase()}${search?' found':' yet'}`} detail={search?'Try another search.':'Add your first record to get started.'}/>} {edit&&<Editor table={table} title={`${edit==='new'?'Add':'Edit'} ${title.toLowerCase()}`} fields={fields} defaults={defaults} initial={edit==='new'?undefined:edit} onClose={()=>setEdit(null)}/>}<Modal open={!!deleting} onClose={()=>setDeleting(null)} title="Delete this record?" description="This cannot be undone. Linked records may need to be removed first."><div className="form-footer"><button className="button secondary" onClick={()=>setDeleting(null)}>Keep record</button><button className="button danger" onClick={async()=>{try{await remove(table,deleting!.id);setDeleting(null);notify('Deleted')}catch(e){notify(errorMessage(e))}}}>Delete</button></div></Modal></section>}
export function UploadBox({meta,onUploaded}:{meta:Partial<Row>;onUploaded?:(r:Row)=>Promise<void>|void}){const {upload,notify}=useStore();const [busy,setBusy]=useState(false),[progress,setProgress]=useState(0);return <label className={`upload-box ${busy?'busy':''}`}><ArrowUpRight size={20}/><strong>{busy?'Uploading…':'Upload images or PDFs'}</strong><span>Multiple files · up to 20 MB each</span><input aria-label="Upload files" type="file" accept="image/png,image/jpeg,image/webp,application/pdf" multiple disabled={busy} onChange={async e=>{const files=Array.from(e.target.files??[]);setBusy(true);try{for(const file of files){const r=await upload(file,meta,setProgress);await onUploaded?.(r)}if(files.length)notify(`${files.length} file(s) uploaded`)}catch(err){notify(errorMessage(err))}finally{setBusy(false);e.target.value=''}}}/>{busy&&<progress max={100} value={progress}/>}</label>}
export function FileList({filter=()=>true}:{filter?:(r:Row)=>boolean}){const {db,openFile,notify}=useStore();const [search,setSearch]=useState('');const rows=db.files.filter(filter).filter(f=>`${f.filename} ${f.category} ${f.tags}`.toLowerCase().includes(search.toLowerCase()));return <><input className="search-input" aria-label="Search files" placeholder="Search filenames, categories or tags…" value={search} onChange={e=>setSearch(e.target.value)}/>{rows.length?rows.map(f=><button key={f.id} className="file-row" onClick={()=>openFile(f).catch(e=>notify(errorMessage(e)))}><FolderOpen/><span><strong>{str(f.filename)}</strong><small>{str(f.category)} · {Math.round(num(f.size_bytes)/1024)} KB</small></span><ArrowUpRight size={18}/></button>):<Empty title="No files found" detail="Upload your academic materials here."/>}</>}
