-- StudyOS initial migration. Run against a new Supabase project.
create extension if not exists pgcrypto;
create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 display_name text not null default 'Student', timezone text not null default 'UTC', locale text not null default 'en',
 daily_study_capacity_minutes integer not null default 180 check(daily_study_capacity_minutes>0),
 daily_score_threshold integer not null default 70 check(daily_score_threshold between 1 and 100),
 preserve_rest_days boolean not null default true, rest_days integer[] not null default '{5}', review_intervals integer[] not null default '{1,3,7,14}',
 sat_target_date date, sat_target_score integer check(sat_target_score between 400 and 1600), ielts_target_date date, ielts_target_band numeric check(ielts_target_band between 0 and 9),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
create policy profile_owner on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create function public.touch_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end $$;
create function public.create_profile() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(nullif(btrim(new.raw_user_meta_data->>'full_name'),''),'Student')); return new; end $$;
create trigger new_user_profile after insert on auth.users for each row execute function public.create_profile();

create table public.subjects (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, color text not null default '#7928ef', sort_order integer not null default 0, unique(id,user_id));
alter table public.subjects enable row level security;
create policy owner_access on public.subjects for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.subjects(user_id);
create trigger touch_updated before update on public.subjects for each row execute function public.touch_updated_at();
create table public.units (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, subject_id uuid not null, sort_order integer not null default 0, unique(id,user_id));
alter table public.units enable row level security;
create policy owner_access on public.units for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.units(user_id);
create trigger touch_updated before update on public.units for each row execute function public.touch_updated_at();
create table public.topics (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, subject_id uuid not null, unit_id uuid, parent_topic_id uuid, status text not null default 'not_started' check(status in ('not_started','learning','needs_practice','good','mastered')), sort_order integer not null default 0, unique(id,user_id));
alter table public.topics enable row level security;
create policy owner_access on public.topics for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.topics(user_id);
create trigger touch_updated before update on public.topics for each row execute function public.touch_updated_at();
create table public.tasks (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, description text not null default '', area text not null default 'Tawjihi', subject_id uuid, topic_id uuid, source text not null default 'manual', priority text not null default 'normal', status text not null default 'planned' check(status in ('planned','in_progress','completed','skipped','cancelled')), due_date date not null default current_date, due_time time, planned_minutes integer not null default 30 check(planned_minutes>0), actual_minutes integer not null default 0 check(actual_minutes>=0), recurrence text not null default 'none', exam_id uuid, sat_session_id uuid, ielts_attempt_id uuid, requirement_id uuid, file_id uuid, mistake_id uuid, auto_generated boolean not null default false, source_metadata text not null default '', completed_at timestamptz, postponed_count integer not null default 0, sort_order integer not null default 0, unique(id,user_id));
alter table public.tasks enable row level security;
create policy owner_access on public.tasks for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.tasks(user_id);
create trigger touch_updated before update on public.tasks for each row execute function public.touch_updated_at();
create table public.study_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, task_id uuid, area text not null default 'Tawjihi', subject_id uuid, status text not null default 'active', elapsed_seconds integer not null default 0 check(elapsed_seconds>=0), running_since timestamptz, completed_at timestamptz, difficulty text not null default 'normal', understanding integer check(understanding between 1 and 5), notes text not null default '', unique(id,user_id));
alter table public.study_sessions enable row level security;
create policy owner_access on public.study_sessions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.study_sessions(user_id);
create trigger touch_updated before update on public.study_sessions for each row execute function public.touch_updated_at();
create table public.calendar_events (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, event_type text not null default 'personal study event', event_date date not null, event_time time, area text not null default 'Tawjihi', subject_id uuid, notes text not null default '', unique(id,user_id));
alter table public.calendar_events enable row level security;
create policy owner_access on public.calendar_events for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.calendar_events(user_id);
create trigger touch_updated before update on public.calendar_events for each row execute function public.touch_updated_at();
create table public.exams (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, subject_id uuid not null, topic_id uuid, exam_type text not null default 'monthly', exam_date date not null, score numeric, maximum_score numeric not null default 100 check(maximum_score>0), teacher text not null default '', notes text not null default '', check(score is null or (score>=0 and score<=maximum_score)), unique(id,user_id));
alter table public.exams enable row level security;
create policy owner_access on public.exams for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.exams(user_id);
create trigger touch_updated before update on public.exams for each row execute function public.touch_updated_at();
create table public.mistakes (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, area text not null default 'Tawjihi', subject_id uuid, topic_id uuid, exam_id uuid, sat_question_id uuid, ielts_attempt_id uuid, file_id uuid, question_number text not null default '', category text not null default 'concept', explanation text not null default '', correct_approach text not null default '', status text not null default 'new', review_date date not null default current_date+1, review_count integer not null default 0, solved_afterward boolean not null default false, unique(id,user_id));
alter table public.mistakes enable row level security;
create policy owner_access on public.mistakes for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.mistakes(user_id);
create trigger touch_updated before update on public.mistakes for each row execute function public.touch_updated_at();
create table public.files (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), filename text not null, mime_type text not null, size_bytes bigint not null check(size_bytes>=0), storage_path text not null, area text not null default 'Inbox', subject_id uuid, topic_id uuid, category text not null default 'notes', tags text[] not null default '{}', source text not null default 'upload', exam_id uuid, task_id uuid, unique(id,user_id));
alter table public.files enable row level security;
create policy owner_access on public.files for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.files(user_id);
create trigger touch_updated before update on public.files for each row execute function public.touch_updated_at();
create table public.inbox_items (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, body text not null default '', file_id uuid, status text not null default 'needs_review' check(status in ('new','analyzing','needs_review','accepted','ignored','error')), area text not null default 'Tawjihi', subject_id uuid, suggested_date date, suggestion_title text not null default '', source text not null default 'manual', accepted_at timestamptz, unique(id,user_id));
alter table public.inbox_items enable row level security;
create policy owner_access on public.inbox_items for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.inbox_items(user_id);
create trigger touch_updated before update on public.inbox_items for each row execute function public.touch_updated_at();
create table public.sat_domains (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, section text not null default 'Math', unique(id,user_id));
alter table public.sat_domains enable row level security;
create policy owner_access on public.sat_domains for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.sat_domains(user_id);
create trigger touch_updated before update on public.sat_domains for each row execute function public.touch_updated_at();
create table public.sat_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, section text not null default 'Math', domain_id uuid, difficulty text not null default 'mixed', planned_question_count integer not null default 10 check(planned_question_count between 1 and 200), status text not null default 'planned', elapsed_seconds integer not null default 0 check(elapsed_seconds>=0), running_since timestamptz, started_at timestamptz, completed_at timestamptz, notes text not null default '', unique(id,user_id));
alter table public.sat_sessions enable row level security;
create policy owner_access on public.sat_sessions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.sat_sessions(user_id);
create trigger touch_updated before update on public.sat_sessions for each row execute function public.touch_updated_at();
create table public.sat_session_questions (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), session_id uuid not null, row_order integer not null, question_identifier text not null default '', my_answer_raw text not null default '', correct_answer_raw text not null default '', normalized_my_answer text generated always as (upper(btrim(my_answer_raw))) stored, normalized_correct_answer text generated always as (upper(btrim(correct_answer_raw))) stored, result text generated always as (case when btrim(my_answer_raw)='' or btrim(correct_answer_raw)='' then 'ungraded' when upper(btrim(my_answer_raw))=upper(btrim(correct_answer_raw)) then 'correct' else 'incorrect' end) stored, mistake_id uuid, unique(session_id,row_order), unique(id,user_id));
alter table public.sat_session_questions enable row level security;
create policy owner_access on public.sat_session_questions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.sat_session_questions(user_id);
create trigger touch_updated before update on public.sat_session_questions for each row execute function public.touch_updated_at();
create table public.ielts_attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, skill text not null check(skill in ('Reading','Listening')), attempt_date date not null, correct integer not null check(correct between 0 and 40), estimated_band numeric check(estimated_band between 0 and 9), elapsed_seconds integer not null default 0 check(elapsed_seconds>=0), question_type text not null default 'mixed', breakdown text not null default '', notes text not null default '', unique(id,user_id));
alter table public.ielts_attempts enable row level security;
create policy owner_access on public.ielts_attempts for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.ielts_attempts(user_id);
create trigger touch_updated before update on public.ielts_attempts for each row execute function public.touch_updated_at();
create table public.ielts_writing_entries (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, task_type text not null default 'Task 2', attempt_date date not null, prompt text not null default '', response text not null default '', elapsed_seconds integer not null default 0 check(elapsed_seconds>=0), estimated_band numeric check(estimated_band between 0 and 9), feedback text not null default '', task_response text not null default '', coherence text not null default '', vocabulary text not null default '', grammar text not null default '', repeated_issues text not null default '', unique(id,user_id));
alter table public.ielts_writing_entries enable row level security;
create policy owner_access on public.ielts_writing_entries for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.ielts_writing_entries(user_id);
create trigger touch_updated before update on public.ielts_writing_entries for each row execute function public.touch_updated_at();
create table public.ielts_speaking_entries (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, part text not null default 'Part 1', attempt_date date not null, elapsed_seconds integer not null default 0 check(elapsed_seconds>=0), notes text not null default '', self_assessment text not null default '', unique(id,user_id));
alter table public.ielts_speaking_entries enable row level security;
create policy owner_access on public.ielts_speaking_entries for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.ielts_speaking_entries(user_id);
create trigger touch_updated before update on public.ielts_speaking_entries for each row execute function public.touch_updated_at();
create table public.universities (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, country text not null default '', program text not null default '', deadline date, platform text not null default '', status text not null default 'researching', url text not null default '', notes text not null default '', unique(id,user_id));
alter table public.universities enable row level security;
create policy owner_access on public.universities for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.universities(user_id);
create trigger touch_updated before update on public.universities for each row execute function public.touch_updated_at();
create table public.scholarships (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, provider text not null default '', university_id uuid, deadline date, coverage text not null default '', status text not null default 'researching', notes text not null default '', unique(id,user_id));
alter table public.scholarships enable row level security;
create policy owner_access on public.scholarships for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.scholarships(user_id);
create trigger touch_updated before update on public.scholarships for each row execute function public.touch_updated_at();
create table public.applications (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, university_id uuid, scholarship_id uuid, status text not null default 'researching', deadline date, notes text not null default '', unique(id,user_id));
alter table public.applications enable row level security;
create policy owner_access on public.applications for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.applications(user_id);
create trigger touch_updated before update on public.applications for each row execute function public.touch_updated_at();
create table public.application_requirements (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, application_id uuid, category text not null default 'Common App', status text not null default 'planned', deadline date, file_id uuid, notes text not null default '', unique(id,user_id));
alter table public.application_requirements enable row level security;
create policy owner_access on public.application_requirements for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.application_requirements(user_id);
create trigger touch_updated before update on public.application_requirements for each row execute function public.touch_updated_at();
create table public.achievements (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, kind text not null default 'Project', organization text not null default '', role text not null default '', start_date date, end_date date, description text not null default '', impact text not null default '', tags text[] not null default '{}', file_id uuid, common_app_candidate boolean not null default false, cv_candidate boolean not null default false, unique(id,user_id));
alter table public.achievements enable row level security;
create policy owner_access on public.achievements for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.achievements(user_id);
create trigger touch_updated before update on public.achievements for each row execute function public.touch_updated_at();
create table public.essays (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, application_id uuid, category text not null default 'Personal statement', response text not null default '', notes text not null default '', unique(id,user_id));
alter table public.essays enable row level security;
create policy owner_access on public.essays for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.essays(user_id);
create trigger touch_updated before update on public.essays for each row execute function public.touch_updated_at();
create table public.exam_files (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), exam_id uuid not null, file_id uuid not null, unique(exam_id,file_id), unique(id,user_id));
alter table public.exam_files enable row level security;
create policy owner_access on public.exam_files for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.exam_files(user_id);
create trigger touch_updated before update on public.exam_files for each row execute function public.touch_updated_at();
create table public.tags (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, unique(user_id,name), unique(id,user_id));
alter table public.tags enable row level security;
create policy owner_access on public.tags for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.tags(user_id);
create trigger touch_updated before update on public.tags for each row execute function public.touch_updated_at();
create table public.file_tags (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), file_id uuid not null, tag_id uuid not null, unique(file_id,tag_id), unique(id,user_id));
alter table public.file_tags enable row level security;
create policy owner_access on public.file_tags for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.file_tags(user_id);
create trigger touch_updated before update on public.file_tags for each row execute function public.touch_updated_at();
create table public.inbox_suggestions (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), inbox_item_id uuid not null, action text not null, status text not null default 'proposed', details jsonb not null default '{}', unique(id,user_id));
alter table public.inbox_suggestions enable row level security;
create policy owner_access on public.inbox_suggestions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create index on public.inbox_suggestions(user_id);
create trigger touch_updated before update on public.inbox_suggestions for each row execute function public.touch_updated_at();
alter table public.units add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.topics add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.topics add foreign key (unit_id,user_id) references public.units(id,user_id) on delete restrict;
alter table public.topics add foreign key (parent_topic_id,user_id) references public.topics(id,user_id) on delete restrict;
alter table public.tasks add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.tasks add foreign key (topic_id,user_id) references public.topics(id,user_id) on delete restrict;
alter table public.tasks add foreign key (exam_id,user_id) references public.exams(id,user_id) on delete restrict;
alter table public.tasks add foreign key (sat_session_id,user_id) references public.sat_sessions(id,user_id) on delete restrict;
alter table public.tasks add foreign key (ielts_attempt_id,user_id) references public.ielts_attempts(id,user_id) on delete restrict;
alter table public.tasks add foreign key (requirement_id,user_id) references public.application_requirements(id,user_id) on delete restrict;
alter table public.tasks add foreign key (file_id,user_id) references public.files(id,user_id) on delete restrict;
alter table public.tasks add foreign key (mistake_id,user_id) references public.mistakes(id,user_id) on delete restrict;
alter table public.study_sessions add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.study_sessions add foreign key (task_id,user_id) references public.tasks(id,user_id) on delete restrict;
alter table public.calendar_events add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.exams add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.exams add foreign key (topic_id,user_id) references public.topics(id,user_id) on delete restrict;
alter table public.mistakes add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.mistakes add foreign key (topic_id,user_id) references public.topics(id,user_id) on delete restrict;
alter table public.mistakes add foreign key (exam_id,user_id) references public.exams(id,user_id) on delete restrict;
alter table public.mistakes add foreign key (ielts_attempt_id,user_id) references public.ielts_attempts(id,user_id) on delete restrict;
alter table public.mistakes add foreign key (file_id,user_id) references public.files(id,user_id) on delete restrict;
alter table public.mistakes add foreign key (sat_question_id,user_id) references public.sat_session_questions(id,user_id) on delete restrict;
alter table public.files add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.files add foreign key (topic_id,user_id) references public.topics(id,user_id) on delete restrict;
alter table public.files add foreign key (exam_id,user_id) references public.exams(id,user_id) on delete restrict;
alter table public.files add foreign key (task_id,user_id) references public.tasks(id,user_id) on delete restrict;
alter table public.inbox_items add foreign key (subject_id,user_id) references public.subjects(id,user_id) on delete restrict;
alter table public.inbox_items add foreign key (file_id,user_id) references public.files(id,user_id) on delete restrict;
alter table public.sat_sessions add foreign key (domain_id,user_id) references public.sat_domains(id,user_id) on delete restrict;
alter table public.sat_session_questions add foreign key (mistake_id,user_id) references public.mistakes(id,user_id) on delete cascade;
alter table public.sat_session_questions add foreign key (session_id,user_id) references public.sat_sessions(id,user_id) on delete cascade;
alter table public.scholarships add foreign key (university_id,user_id) references public.universities(id,user_id) on delete restrict;
alter table public.applications add foreign key (university_id,user_id) references public.universities(id,user_id) on delete restrict;
alter table public.applications add foreign key (scholarship_id,user_id) references public.scholarships(id,user_id) on delete restrict;
alter table public.application_requirements add foreign key (file_id,user_id) references public.files(id,user_id) on delete restrict;
alter table public.application_requirements add foreign key (application_id,user_id) references public.applications(id,user_id) on delete restrict;
alter table public.achievements add foreign key (file_id,user_id) references public.files(id,user_id) on delete restrict;
alter table public.essays add foreign key (application_id,user_id) references public.applications(id,user_id) on delete restrict;
alter table public.exam_files add foreign key (exam_id,user_id) references public.exams(id,user_id) on delete cascade;
alter table public.exam_files add foreign key (file_id,user_id) references public.files(id,user_id) on delete cascade;
alter table public.file_tags add foreign key (file_id,user_id) references public.files(id,user_id) on delete cascade;
alter table public.file_tags add foreign key (tag_id,user_id) references public.tags(id,user_id) on delete cascade;
alter table public.inbox_suggestions add foreign key (inbox_item_id,user_id) references public.inbox_items(id,user_id) on delete cascade;
create index sat_identifier_lookup on public.sat_session_questions(user_id,question_identifier);
create index task_date_lookup on public.tasks(user_id,due_date);
create index mistake_review_lookup on public.mistakes(user_id,review_date);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('academic-files','academic-files',false,20971520,array['application/pdf','image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy academic_files_read on storage.objects for select to authenticated using(bucket_id='academic-files' and (storage.foldername(name))[1]=auth.uid()::text);
create policy academic_files_insert on storage.objects for insert to authenticated with check(bucket_id='academic-files' and (storage.foldername(name))[1]=auth.uid()::text);
create policy academic_files_delete on storage.objects for delete to authenticated using(bucket_id='academic-files' and (storage.foldername(name))[1]=auth.uid()::text);
create or replace function public.create_sat_practice(p_title text,p_section text,p_domain uuid,p_difficulty text,p_ids text[]) returns uuid language plpgsql security invoker set search_path=public as $$
declare sid uuid; q text; n integer:=0;
begin
 if cardinality(p_ids)<1 or cardinality(p_ids)>200 then raise exception 'Choose 1–200 questions'; end if;
 insert into sat_sessions(title,section,domain_id,difficulty,planned_question_count) values(p_title,p_section,p_domain,p_difficulty,cardinality(p_ids)) returning id into sid;
 foreach q in array p_ids loop
 insert into sat_session_questions(session_id,row_order,question_identifier) values(sid,n,btrim(q)); n:=n+1;
 end loop;
 return sid;
end $$;
create or replace function public.accept_inbox(p_id uuid,p_title text,p_date date,p_area text,p_subject uuid,p_task boolean,p_event boolean,p_file boolean) returns void language plpgsql security invoker set search_path=public as $$
declare item inbox_items;
begin
 select * into item from inbox_items where id=p_id and user_id=auth.uid() for update;
 if not found then raise exception 'Import not found'; end if;
 if item.status='accepted' then raise exception 'Import already accepted'; end if;
 if p_task then insert into tasks(title,area,subject_id,due_date,source,source_metadata) values(p_title,p_area,p_subject,p_date,'teacher_import',p_id::text); end if;
 if p_event then insert into calendar_events(title,event_date,area,subject_id,event_type) values(p_title,p_date,p_area,p_subject,'school quiz'); end if;
 if p_file and item.file_id is not null then update files set area=p_area,subject_id=p_subject where id=item.file_id; end if;
 update inbox_items set status='accepted',accepted_at=now(),area=p_area,subject_id=p_subject,suggested_date=p_date,suggestion_title=p_title where id=p_id;
end $$;
-- Functions remain invoker-scoped. RLS applies to every write and composite FKs block cross-user links.
revoke execute on function public.create_sat_practice(text,text,uuid,text,text[]) from public;
grant execute on function public.create_sat_practice(text,text,uuid,text,text[]) to authenticated;
revoke execute on function public.accept_inbox(uuid,text,date,text,uuid,boolean,boolean,boolean) from public;
grant execute on function public.accept_inbox(uuid,text,date,text,uuid,boolean,boolean,boolean) to authenticated;
